name:                coding-practice
version:             0.1.0.0
github:              "jakobbeckmann/coding-practice"
license:             BSD3
author:              "Jakob Beckmann"
copyright:           "2020 Jakob Beckmann"

extra-source-files: []

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6

library:
  source-dirs: src

executables:
  coding-practice-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coding-practice

tests:
  coding-practice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coding-practice
    - hspec
    - QuickCheck
