dist: trusty
branches:
  only:
    - master

matrix:
  include:
    - language: crystal
      crystal: latest
      before_script:
        - cd crystal
    - language: rust
      rust: stable
      before_script:
        - cd rust
