dist: trusty
branches:
  only:
    - master

matrix:
  include:
    - language: crystal
      crystal: latest
      before_script:
        - cd crystal
    - language: rust
      rust: stable
      before_script:
        - cd rust
    - language: node_js
      node_js: "10"
      before_script:
        - cd js
        - yarn
    - language: perl6
      perl6: latest
      before_script:
          - cd perl6
