dist: trusty
branches:
  only:
    - master

matrix:
  include:
    - language: rust
      rust: stable
      before_script:
        - cd rust
    - language: elixir
      elixir: "1.9.2"
      before_install:
        - cd elixir
    - language: node_js
      node_js: "10"
      before_script:
        - cd js
        - yarn
    - language: perl6
      perl6: "2019.03"
      before_script:
          - cd perl6
    - name: nim
      sudo: required
      services:
        - docker
      before_install:
        - docker pull nimlang/nim
      script:
        - cd nim
        - docker run nimlang/nim nim --version
        - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c "nimble install -dy && nimble test"
