---
os: linux
dist: trusty
branches:
  only:
    - master

# Caching stack builds for haskell
cache:
  directories:
    - $HOME/.stack

jobs:
  include:
    - language: haskell
      before_install:
        - mkdir -p ~/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
        - travis_retry curl -L
          https://get.haskellstack.org/stable/linux-x86_64.tar.gz |
          tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      install:
        - echo "no install required"
      before_script:
        - cd haskell
      script:
        - stack --no-terminal --skip-ghc-check test
    - language: rust
      rust: stable
      before_script:
        - cd rust
    - language: elixir
      elixir: "1.9.2"
      before_install:
        - cd elixir
    - language: node_js
      before_script:
        - cd js
        - yarn
      node_js: "10"
    - language: perl6
      before_script:
        - cd perl6
      perl6: "2019.03"
    - name: nim
      services:
        - docker
      before_install:
        - docker pull nimlang/nim
      script:
        - cd nim
        - docker run nimlang/nim nim --version
        - docker run -v "$(pwd):/project" -w /project nimlang/nim sh -c
          "nimble install -dy && nimble test"
